<a href="https://colab.research.google.com/github/DorotaJanosz/neural-network-course/blob/master/01_basics/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###Skalar

In [3]:
scalar = 3
print(scalar)
print(type(scalar))

3
<class 'int'>


In [4]:
scalar = 3.0
print(scalar)
print(type(scalar))

3.0
<class 'float'>


###Wektor

In [7]:
vector = np.array([2, 4, -6, 5])
print(vector)
print(type(vector))
print(f'Rozmiar wektora {vector.shape}')
print(f'Typ danych wektora {vector.dtype}')
print(f'Rząd wektora {vector.ndim}')
print(f'Długość wektora {len(vector)}')

[ 2  4 -6  5]
<class 'numpy.ndarray'>
Rozmiar wektora (4,)
Typ danych wektora int64
Rząd wektora 1
Długość wektora 4


In [9]:
vector = np.array([2, 4, -6, 5], dtype='float')
print(vector)
print(f'Typ danych wektora {vector.dtype}')

[ 2.  4. -6.  5.]
Typ danych wektora float64


###Macierz

In [13]:
array = np.array([[2, 6, 3],
                  [5, -3, 4]])
print(array)
print(type(array))
print(f'Rozmiar wektora {array.shape}')
print(f'Typ danych wektora {array.dtype}')
print(f'Rząd wektora {array.ndim}')
print(f'Długość wektora {len(array)}')

[[ 2  6  3]
 [ 5 -3  4]]
<class 'numpy.ndarray'>
Rozmiar wektora (2, 3)
Typ danych wektora int64
Rząd wektora 2
Długość wektora 2


###Tensor

In [16]:
tensor = np.array([
                   [[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [3, 7, 3]]
])
print(tensor)
print(type(tensor))
print(f'Rozmiar wektora {tensor.shape}')
print(f'Typ danych wektora {tensor.dtype}')
print(f'Rząd wektora {tensor.ndim}')
print(f'Długość wektora {len(tensor)}')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]]
<class 'numpy.ndarray'>
Rozmiar wektora (2, 2, 3)
Typ danych wektora int64
Rząd wektora 3
Długość wektora 2


In [17]:
tensor = np.array([
                   [[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [3, 7, 3]],
                   [[1, 5, 8],
                    [6, 3, 5]]
])
print(tensor)
print(type(tensor))
print(f'Rozmiar wektora {tensor.shape}')
print(f'Typ danych wektora {tensor.dtype}')
print(f'Rząd wektora {tensor.ndim}')
print(f'Długość wektora {len(tensor)}')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]

 [[1 5 8]
  [6 3 5]]]
<class 'numpy.ndarray'>
Rozmiar wektora (3, 2, 3)
Typ danych wektora int64
Rząd wektora 3
Długość wektora 3


In [18]:
tensor[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
tensor[1:]

array([[[7, 8, 9],
        [3, 7, 3]],

       [[1, 5, 8],
        [6, 3, 5]]])