<a href="https://colab.research.google.com/github/DorotaJanosz/neural-network-course/blob/master/01_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

###ReLU - Rectified linear unit

In [2]:
def max_relu(x):
  return max(0.0, x)

In [3]:
for i in [-10, -5, 0, 5, 10]:
  print(max_relu(i))

0.0
0.0
0.0
5
10


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-3.0443100704284785,
 -1.4946304361918545,
 -1.4453779225042611,
 -1.3574656726439114,
 -1.3051844948801983,
 -1.2614041088692294,
 -1.1099965893845378,
 -0.9383960468129348,
 -0.7411157626995859,
 -0.7218598520382761,
 -0.5073423225210305,
 -0.46581632493400077,
 -0.4345981380840842,
 -0.3306511646609314,
 -0.32489880506274893,
 -0.2631488612770985,
 -0.19122344997422672,
 -0.17307281088202303,
 -0.10923516785891307,
 -0.09134377236232105,
 -0.07476765815790638,
 -0.010043686728883998,
 0.013270420611945714,
 0.03853187241278112,
 0.058702619081810584,
 0.0956403996950784,
 0.10877786772280128,
 0.12322959655232921,
 0.126182624640076,
 0.16218136431490301,
 0.3340370170751573,
 0.3423215657079382,
 0.38862295392232976,
 0.40081272873297574,
 0.7317900763183506,
 0.7369163906445458,
 0.7523701077722457,
 0.772900505212867,
 0.8983112781362929,
 1.0852724848930402,
 1.1495216362733884,
 1.1840798016235885,
 1.432549165260396,
 1.48715253220558,
 1.7351174347776412,
 1.7511241833502815

In [6]:
max_relu_data = np.array([max_relu(i) for i in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.01327 , 0.038532,
       0.058703, 0.09564 , 0.108778, 0.12323 , 0.126183, 0.162181,
       0.334037, 0.342322, 0.388623, 0.400813, 0.73179 , 0.736916,
       0.75237 , 0.772901, 0.898311, 1.085272, 1.149522, 1.18408 ,
       1.432549, 1.487153, 1.735117, 1.751124, 1.816154, 1.910615,
       2.545368, 2.819962])

In [7]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -3.044310            0.0
1 -1.494630            0.0
2 -1.445378            0.0
3 -1.357466            0.0
4 -1.305184            0.0

In [9]:
px.line(df, x='data', y='max_relu_data', title='ReLU Function', width=700, height=400)

###Funkcja sigmoid

In [13]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [14]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
  print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [17]:
data = 3 * np.random.randn(50) 
data = sorted(data)
data

[-4.543376919772645,
 -4.200698515192526,
 -4.053795137432619,
 -3.867906035886533,
 -3.6523656410829908,
 -3.36264648662779,
 -2.7789349499976077,
 -2.1024359331072704,
 -2.0919478232921738,
 -1.9649357028842807,
 -1.891417578589738,
 -1.8869590953259712,
 -1.6270824874084637,
 -1.5348340245843093,
 -1.2913049251629327,
 -0.707836038453381,
 -0.46196602996905145,
 -0.1271456212810629,
 -0.04009309487946755,
 -0.0003869102763446303,
 0.05305072821149734,
 0.08025770124294768,
 0.10783782789365218,
 0.26535885260795167,
 0.5122763443936349,
 0.601908852302556,
 0.776530084756155,
 1.0952106874707894,
 1.5814656893419192,
 1.6434937672432417,
 1.6479963076355904,
 1.7315711403752232,
 2.0683993820291926,
 2.138080077402125,
 2.2733009789610383,
 2.2783062401636345,
 2.285325576797491,
 2.3565053962239224,
 3.1199542057693037,
 3.121356450627993,
 3.3148207358317197,
 3.320476071877204,
 3.420418989245989,
 3.434252455938199,
 3.7178949537008634,
 4.384960950792479,
 4.976557406734296,
 5

In [18]:
sigmoid_data = np.array([sigmoid(x) for x in data])
sigmoid_data

array([0.010525, 0.014764, 0.01706 , 0.020474, 0.025274, 0.033483,
       0.058473, 0.10886 , 0.109882, 0.122934, 0.131083, 0.131592,
       0.16423 , 0.177288, 0.215632, 0.330077, 0.38652 , 0.468256,
       0.489978, 0.499903, 0.51326 , 0.520054, 0.526933, 0.565953,
       0.62534 , 0.646093, 0.684932, 0.749362, 0.829412, 0.83801 ,
       0.83862 , 0.849613, 0.887794, 0.89455 , 0.906642, 0.907064,
       0.907654, 0.91345 , 0.957708, 0.957765, 0.964934, 0.965125,
       0.968337, 0.968758, 0.976291, 0.98769 , 0.993149, 0.993688,
       0.997728, 0.999982])

In [19]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -4.543377      0.010525
1 -4.200699      0.014764
2 -4.053795      0.017060
3 -3.867906      0.020474
4 -3.652366      0.025274

In [21]:
px.line(df, x='data', y='sigmoid_data', title='Sigmoid Function', width=700, height=400)

###Tanh Function

In [26]:
def tanh(x):
  return np.tanh(x)

In [27]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-3.7262727350873943,
 -3.5434646095479128,
 -3.125455620337041,
 -3.0520727067800966,
 -3.0420623185809528,
 -2.9956370345098255,
 -2.882994902495473,
 -2.7936663100643746,
 -2.5879197151113686,
 -2.566018002537123,
 -2.4386472841496,
 -2.2976096359654776,
 -2.2414600681922168,
 -2.080521116475951,
 -2.0438013108243633,
 -2.0030012400716877,
 -1.9133359463345019,
 -1.8861539074360925,
 -1.754784802151825,
 -1.7296113690696973,
 -1.7106155562604382,
 -1.7066475914917023,
 -1.4449272994203974,
 -1.436779718014898,
 -1.4276203095476345,
 -1.349023536625041,
 -1.2944510368883617,
 -1.2755592076655728,
 -1.2527092709018577,
 -1.169857841789448,
 -1.0785510843227375,
 -1.0024884135496936,
 -0.9880916885649216,
 -0.9714980681018114,
 -0.9313326500356508,
 -0.8774517169077592,
 -0.827016339768952,
 -0.8058966266655077,
 -0.7020173190903755,
 -0.6609544226141902,
 -0.6255017745007985,
 -0.5764420462189059,
 -0.5656387222158445,
 -0.5303691772224521,
 -0.5297851210132769,
 -0.49671110158869364,

In [28]:
tanh_data = np.array([tanh(x) for x in data])
tanh_data

array([-0.998841, -0.998329, -0.99615 , -0.995543, -0.995453, -0.995012,
       -0.993755, -0.992538, -0.988761, -0.98826 , -0.98488 , -0.980002,
       -0.977652, -0.969296, -0.966995, -0.964239, -0.957365, -0.955036,
       -0.941918, -0.93901 , -0.936723, -0.936235, -0.894685, -0.893048,
       -0.891178, -0.873823, -0.860288, -0.855297, -0.849042, -0.824227,
       -0.792661, -0.762637, -0.756547, -0.749362, -0.731215, -0.70514 ,
       -0.678871, -0.66732 , -0.605647, -0.578998, -0.554947, -0.520075,
       -0.512149, -0.485663, -0.485217, -0.459527, -0.438336, -0.378324,
       -0.317793, -0.309092, -0.26079 , -0.053383,  0.028223,  0.074895,
        0.162416,  0.181245,  0.213404,  0.218591,  0.317275,  0.459546,
        0.491828,  0.521158,  0.603267,  0.768468,  0.796461,  0.800314,
        0.804449,  0.810619,  0.832434,  0.851349,  0.869653,  0.871292,
        0.874793,  0.877499,  0.878596,  0.879359,  0.890877,  0.905937,
        0.923039,  0.930045,  0.933003,  0.959253, 

In [29]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -3.726273  -0.998841
1 -3.543465  -0.998329
2 -3.125456  -0.996150
3 -3.052073  -0.995543
4 -3.042062  -0.995453

In [30]:
px.line(df, x='data', y='tanh_data', title='Tanh Function', width=700, height=400)

Sofmax Function

In [35]:
def softmax(x):
  e_x = np.exp(x)
  denominator = np.sum(e_x, axis=1)
  denominator = denominator[:, np.newaxis]
  return e_x / denominator

In [38]:
data = np.random.randn(4, 5)
data

array([[ 0.767785, -1.107206, -0.258829,  0.533724, -0.137074],
       [ 0.414178,  1.00261 , -0.276099, -0.278463, -0.273668],
       [ 1.563987,  0.552245,  0.17517 ,  1.826049,  0.412907],
       [-1.05253 ,  1.417442, -0.920041,  2.249364, -0.722149]])

In [39]:
result = softmax(data)
result

array([[0.369346, 0.056642, 0.132306, 0.292269, 0.149437],
       [0.23226 , 0.418339, 0.116464, 0.116189, 0.116747],
       [0.309707, 0.112605, 0.077232, 0.402497, 0.097959],
       [0.023519, 0.278041, 0.026851, 0.638863, 0.032726]])