<a href="https://colab.research.google.com/github/DorotaJanosz/neural-network-course/blob/master/01_basics/05_regression_metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([146.32954088,  90.69119301,  83.33459532,  82.30092328,
        88.27607498,  64.14386022,  84.26070391,  99.46947198,
        83.4889716 , 115.33794706,  92.97959127,  66.60901878,
        66.36006617, 116.28662046,  75.82989575,  76.69761614,
       121.98574341,  76.80428959, 118.82844562, 119.81058327,
        70.11684671, 100.58729888,  80.81731877,  95.44156134,
       147.74960444,  95.13648245, 119.67216454, 102.0148655 ,
       126.67162452, 114.00697324,  65.92334218, 119.01168309,
        70.93954405,  88.94576396, 109.38058775,  81.41064008,
       106.705619  ,  97.16369784,  97.29648077, 122.07533963,
       105.7232487 , 157.12777041,  98.48377197,  98.13265803,
       113.34470101, 110.97372681, 115.17919245,  97.11893436,
        93.11098432,  64.59946533])

In [3]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([148.83158173, 101.44027014, 102.35068166,  72.15443975,
        93.30064295,  69.86319453,  79.26748278,  99.00239432,
        84.40656103, 122.20595464,  76.18000996,  64.64429783,
        53.29061352,  96.63351385,  77.50035193,  83.47021267,
       122.97634883,  60.71544892, 129.79630474, 120.80883277,
        90.18617667, 102.17877629,  81.68221026,  93.37905699,
       143.81404061,  90.970965  , 104.89921618,  96.86510669,
       133.69620979, 103.45403763,  57.83921093, 116.30827756,
        62.02818881,  73.29357524, 109.2131304 ,  63.79966727,
       115.98543304,  95.51148707,  99.24302452, 123.19119286,
        91.43362901, 166.61653039,  86.79809313,  93.53394487,
       111.24852504, 111.82797608, 119.63539097,  94.18365987,
        97.23724832,  71.48184072])

In [4]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

y_true      y_pred
0  146.329541  148.831582
1   90.691193  101.440270
2   83.334595  102.350682
3   82.300923   72.154440
4   88.276075   93.300643

In [5]:
results['error'] = results['y_true'] - results['y_pred']
results.head()

y_true      y_pred      error
0  146.329541  148.831582  -2.502041
1   90.691193  101.440270 -10.749077
2   83.334595  102.350682 -19.016086
3   82.300923   72.154440  10.146484
4   88.276075   93.300643  -5.024568

###MAE

In [6]:
from tensorflow.keras.losses import mean_absolute_error
mean_absolute_error(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=7.082114186990315>

###MSE

In [7]:
from tensorflow.keras.losses import mean_squared_error
mse = mean_squared_error(y_true, y_pred)
mse

<tf.Tensor: shape=(), dtype=float64, numpy=83.80141225759127>

###RMSE

In [8]:
np.sqrt(mse)

9.154311129603979

###Max Error

In [9]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

20.06932995767238

###R2 Score

In [10]:
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.8244587195227727