<a href="https://colab.research.google.com/github/DorotaJanosz/neural-network-course/blob/master/02_keras/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Załadowanie bibliotek

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

###Wprowadzenie - pierwszy model

In [2]:
from tensorflow.keras.models import Sequential

model = Sequential() 
print(model)

In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,))) 


In [4]:
model.summary() 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.add(Dense(units=2)) 

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


###Funkcje aktywacji

In [7]:
from tensorflow.keras.activations import linear 

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data

data    linear
0   -2.562772 -2.562772
1   -2.337816 -2.337816
2   -2.296015 -2.296015
3   -2.287328 -2.287328
4   -2.275743 -2.275743
..        ...       ...
195  1.936599  1.936599
196  2.044867  2.044867
197  2.113374  2.113374
198  2.178923  2.178923
199  2.737700  2.737700

[200 rows x 2 columns]

In [8]:
px.line(data, x='data', y='linear', width=800)

In [9]:
from tensorflow.keras.activations import sigmoid 

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data

data   sigmoid
0   -2.359608  0.086305
1   -2.085399  0.110524
2   -1.833124  0.137867
3   -1.786431  0.143511
4   -1.774614  0.144970
..        ...       ...
195  2.215809  0.901660
196  2.218397  0.901889
197  2.518571  0.925434
198  2.652328  0.934154
199  3.024462  0.953667

[200 rows x 2 columns]

In [10]:
px.line(data, x='data', y='sigmoid', width=800)

In [11]:
from tensorflow.keras.activations import relu

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data

data      relu
0   -3.312873  0.000000
1   -2.390710  0.000000
2   -2.195918  0.000000
3   -2.093092  0.000000
4   -2.051596  0.000000
..        ...       ...
195  2.150541  2.150541
196  2.172374  2.172374
197  2.194011  2.194011
198  2.386373  2.386373
199  2.524636  2.524636

[200 rows x 2 columns]

In [12]:
px.line(data, x='data', y='relu', width=800)

In [13]:
from tensorflow.keras.activations import tanh

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data

data      tanh
0   -2.077656 -0.969122
1   -2.031997 -0.966220
2   -2.030382 -0.966112
3   -1.847710 -0.951530
4   -1.716268 -0.937412
..        ...       ...
195  1.743313  0.940610
196  1.942336  0.959719
197  2.053446  0.967615
198  2.073530  0.968871
199  2.466661  0.985698

[200 rows x 2 columns]

In [14]:
px.line(data, x='data', y='tanh', width=800)

###Przygotowanie modelu

In [15]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


###Kompilacja modelu

In [16]:
#Klasyfikacja binarna
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

#Klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

#Regresja
model.compile(optimizer='rmsprop', loss='mse')

###Trenowanie modelu

Za dane wejściowe do modelu należy przekazać Numpy arrays:

    epochs - krotność przejścia danych przez sieć w procesie uczenia
    batch_size - rozmiar wsadu po którym następuje aktualizacja wag
    validation_split - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
    validation_data - (x_val, y_val) - dane wykorzystane do walidacji modelu


###Przykład - klasyfikacja binarna

In [17]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [18]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 [==============================] - 0s 1ms/step - loss: 0.8228 - accuracy: 0.5250
Epoch 2/20
32/32 [==============================] - 0s 1ms/step - loss: 0.7105 - accuracy: 0.5770
Epoch 3/20
32/32 [==============================] - 0s 1ms/step - loss: 0.6533 - accuracy: 0.6180
Epoch 4/20
32/32 [==============================] - 0s 1ms/step - loss: 0.6118 - accuracy: 0.6620
Epoch 5/20
32/32 [==============================] - 0s 1ms/step - loss: 0.5768 - accuracy: 0.7130
Epoch 6/20
32/32 [==============================] - 0s 1ms/step - loss: 0.5463 - accuracy: 0.7340
Epoch 7/20
32/32 [==============================] - 0s 1ms/step - loss: 0.5187 - accuracy: 0.7710
Epoch 8/20
32/32 [==============================] - 0s 1ms/step - loss: 0.4922 - accuracy: 0.8030
Epoch 9/20
32/32 [==============================] - 0s 1ms/step - loss: 0.4677 - accuracy: 0.8300
Epoch 10/20
32/32 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.8380
Epoch 11/20
32/32 [

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 [==============================] - 0s 1ms/step - loss: 0.7948 - accuracy: 0.4940
Epoch 2/20
34/34 [==============================] - 0s 1ms/step - loss: 0.7012 - accuracy: 0.5570
Epoch 3/20
34/34 [==============================] - 0s 1ms/step - loss: 0.6479 - accuracy: 0.6340
Epoch 4/20
34/34 [==============================] - 0s 1ms/step - loss: 0.6067 - accuracy: 0.6770
Epoch 5/20
34/34 [==============================] - 0s 1ms/step - loss: 0.5737 - accuracy: 0.7190
Epoch 6/20
34/34 [==============================] - 0s 1ms/step - loss: 0.5439 - accuracy: 0.7470
Epoch 7/20
34/34 [==============================] - 0s 1ms/step - loss: 0.5183 - accuracy: 0.7770
Epoch 8/20
34/34 [==============================] - 0s 1ms/step - loss: 0.4930 - accuracy: 0.7980
Epoch 9/20
34/34 [==============================] - 0s 1ms/step - loss: 0.4692 - accuracy: 0.8220
Epoch 10/20
34/34 [==============================] - 0s 1ms/step - loss: 0.4466 - accuracy: 0.8270
Epoch 11/20
34/34 [

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
25/25 [==============================] - 0s 14ms/step - loss: 0.7821 - accuracy: 0.4888 - val_loss: 0.7930 - val_accuracy: 0.5050
Epoch 2/20
25/25 [==============================] - 0s 2ms/step - loss: 0.7036 - accuracy: 0.5487 - val_loss: 0.7810 - val_accuracy: 0.4850
Epoch 3/20
25/25 [==============================] - 0s 2ms/step - loss: 0.6561 - accuracy: 0.5913 - val_loss: 0.7774 - val_accuracy: 0.4750
Epoch 4/20
25/25 [==============================] - 0s 2ms/step - loss: 0.6163 - accuracy: 0.6400 - val_loss: 0.7773 - val_accuracy: 0.4750
Epoch 5/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5817 - accuracy: 0.6938 - val_loss: 0.7822 - val_accuracy: 0.5000
Epoch 6/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5514 - accuracy: 0.7262 - val_loss: 0.7865 - val_accuracy: 0.5000
Epoch 7/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5226 - accuracy: 0.7588 - val_loss: 0.7933 - val_accuracy: 0.4850
Epoch 8/20
25/25 [=

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [22]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [23]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [24]:
model.predict(test_data)

array([[0.24927667],
       [0.5882062 ],
       [0.17208534],
       [0.09572521],
       [0.43863866]], dtype=float32)

In [25]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.24927667],
       [0.5882062 ],
       [0.17208534],
       [0.09572521],
       [0.43863866]], dtype=float32)

In [26]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

###Klasyfikacja wieloklasowa

In [27]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [28]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [29]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10,activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 0s 6ms/step - loss: 2.3340 - accuracy: 0.1100 - val_loss: 2.3388 - val_accuracy: 0.0750
Epoch 2/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2996 - accuracy: 0.1275 - val_loss: 2.3378 - val_accuracy: 0.0950
Epoch 3/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2891 - accuracy: 0.1350 - val_loss: 2.3315 - val_accuracy: 0.0900
Epoch 4/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2759 - accuracy: 0.1488 - val_loss: 2.3361 - val_accuracy: 0.0900
Epoch 5/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2696 - accuracy: 0.1787 - val_loss: 2.3266 - val_accuracy: 0.1000
Epoch 6/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2589 - accuracy: 0.1663 - val_loss: 2.3386 - val_accuracy: 0.0900
Epoch 7/30
25/25 [==============================] - 0s 2ms/step - loss: 2.2471 - accuracy: 0.1500 - val_loss: 2.3358 - val_accuracy: 0.0900
Epoch 8/30
25/25 [==

In [31]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.1349581 , 0.09977027, 0.08281474, 0.10143214, 0.08190867,
        0.10435108, 0.03633464, 0.13077119, 0.06507026, 0.16258885],
       [0.0947535 , 0.17575559, 0.09827588, 0.12443815, 0.05754135,
        0.08044242, 0.10166428, 0.08340341, 0.06667202, 0.11705343],
       [0.10435034, 0.1488414 , 0.09081852, 0.13499333, 0.07230335,
        0.10341369, 0.06667937, 0.10505772, 0.07609865, 0.09744361],
       [0.12353323, 0.08148508, 0.07645059, 0.08980657, 0.05292844,
        0.13967794, 0.07796886, 0.09998152, 0.15023014, 0.10793763],
       [0.09878808, 0.05013249, 0.08481327, 0.12077834, 0.1015537 ,
        0.13304764, 0.06246091, 0.1867147 , 0.09270759, 0.06900328],
       [0.12543905, 0.11265302, 0.07973887, 0.151809  , 0.06804533,
        0.07390458, 0.05058726, 0.18025199, 0.0462402 , 0.11133071],
       [0.05873268, 0.06742679, 0.12781963, 0.08381173, 0.15750784,
        0.06534126, 0.07858865, 0.09713529, 0.08125333, 0.18238275],
       [0.12389658, 0.09314913, 0.0620197

In [32]:
model.predict_classes(test_data)

array([9, 1, 1, 8, 7, 7, 9, 7, 7, 6])

###Regresja

In [34]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [37]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))
model.compile(optimizer='rmsprop', loss='mse') 
model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 0s 5ms/step - loss: 584.7969 - val_loss: 388.4009
Epoch 2/30
25/25 [==============================] - 0s 2ms/step - loss: 312.3819 - val_loss: 235.3833
Epoch 3/30
25/25 [==============================] - 0s 2ms/step - loss: 208.9225 - val_loss: 202.0332
Epoch 4/30
25/25 [==============================] - 0s 2ms/step - loss: 192.3995 - val_loss: 204.9398
Epoch 5/30
25/25 [==============================] - 0s 2ms/step - loss: 192.3871 - val_loss: 202.8836
Epoch 6/30
25/25 [==============================] - 0s 2ms/step - loss: 191.4872 - val_loss: 201.8960
Epoch 7/30
25/25 [==============================] - 0s 2ms/step - loss: 190.8488 - val_loss: 204.9449
Epoch 8/30
25/25 [==============================] - 0s 2ms/step - loss: 190.7511 - val_loss: 201.9955
Epoch 9/30
25/25 [==============================] - 0s 2ms/step - loss: 190.7074 - val_loss: 203.1449
Epoch 10/30
25/25 [==============================] - 0s 2ms/step - loss: 189.5198 

In [38]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))
model.compile(optimizer='rmsprop', loss='mae', metrics=['mse']) 
model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 0s 6ms/step - loss: 19.8312 - mse: 563.2209 - val_loss: 16.1752 - val_mse: 388.4661
Epoch 2/30
25/25 [==============================] - 0s 2ms/step - loss: 14.6304 - mse: 314.1808 - val_loss: 13.0659 - val_mse: 240.7783
Epoch 3/30
25/25 [==============================] - 0s 2ms/step - loss: 12.2583 - mse: 210.8595 - val_loss: 12.0207 - val_mse: 202.1671
Epoch 4/30
25/25 [==============================] - 0s 2ms/step - loss: 11.7962 - mse: 192.9090 - val_loss: 12.0158 - val_mse: 203.3174
Epoch 5/30
25/25 [==============================] - 0s 2ms/step - loss: 11.7746 - mse: 191.9245 - val_loss: 12.0164 - val_mse: 203.6443
Epoch 6/30
25/25 [==============================] - 0s 2ms/step - loss: 11.7389 - mse: 191.6393 - val_loss: 12.0152 - val_mse: 202.0058
Epoch 7/30
25/25 [==============================] - 0s 2ms/step - loss: 11.7738 - mse: 192.0383 - val_loss: 12.0140 - val_mse: 203.1174
Epoch 8/30
25/25 [==============================